name: autogl
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  http: ^1.3.0
  dart_jsonwebtoken: ^2.17.0
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^6.1.3
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  local_auth: ^2.3.0
  logger: ^2.5.0
  path_provider: ^2.1.5
  geolocator: ^13.0.4
  async: ^2.11.0
  skeletonizer: ^1.4.3
  flutter_skeleton_ui: ^0.0.6
  transparent_image: ^2.0.1
  animated_text_kit: ^4.2.3
  loading_indicator: ^3.1.1
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF" # Color de fondo para íconos adaptativos (Android)
  adaptive_icon_foreground: "assets/logo.png" # Ícono adaptativo (opcional)

flutter_native_splash:
  color: "#000000" # Color de fondo
  image: assets/logo.png # Imagen que quieres mostrar
  android: true
  ios: true
  android_gravity: center # Centra la imagen en Android
  ios_content_mode: center # Centra la imagen en iOS
  fullscreen: true # Opción para que sea pantalla completa
